# Setup
title:        JW Zhu's blog
tagline:      An enthusiastic program designer
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Jiawei Zhu
  url:        http://zhujiawei6000.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown